ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += netdev_tap
endif

ifneq (,$(filter mtd,$(USEMODULE)))
    USEMODULE += mtd_native
endif

ifneq (,$(filter socket_zep,$(USEMODULE)))
  USEMODULE += netdev_ieee802154
  USEMODULE += checksum
  USEMODULE += random
endif
